spec:
  structures:
    - content_blocks
  label: Tagnévsor
  description: Members grouped by membership category
  icon: groups
  tags: ["members"]

blueprint:
  title: Tagjaink
  title_suffix:
  description:
  groups:
    - label: Elnökség
      members:
        - name: Példa Névsor
          image:
          modal_image:
          bio:

preview:

_inputs:
  description:
    type: markdown
  groups[*].members[*].image:
    type: image
    comment: Kis kör alakú előnézeti kép a névsor csempén. Ha üres, monogram jelenik meg helyette.
  groups[*].members[*].modal_image:
    type: image
    comment: >-
      Nagyobb kép a névre kattintva megnyíló ablakban. Ha üres, az előnézeti kép
      (image) jelenik meg helyette. Külön kép megadása hasznos, ha az előnézeti
      kép szoros körvágása miatt az arc nincs középen.
  groups[*].members[*].bio:
    type: text
    comment: Rövid, opcionális leírás - csak akkor jelenik meg, ha ki van töltve.
